# Generated by Django 5.1.5 on 2025-01-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_login', models.CharField(max_length=50, unique=True)),
                ('user_first_name', models.CharField(max_length=255)),
                ('user_last_name', models.CharField(max_length=255)),
                ('user_surname', models.CharField(default='', max_length=255)),
                ('user_phone', models.CharField(default='', max_length=20)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_sex', models.CharField(max_length=1)),
                ('user_birthday', models.DateField()),
                ('user_role', models.CharField(max_length=50)),
                ('user_tax_number', models.CharField(default='', max_length=25)),
                ('user_description', models.TextField()),
                ('user_created_at', models.DateTimeField(auto_now_add=True)),
                ('user_changed_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
    ]
