# Generated by Django 5.1.5 on 2025-01-26 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_group_id_ref',
            field=models.ForeignKey(blank=True, db_column='user_group_id_ref', null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.usergroup'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.ForeignKey(blank=True, db_column='user_role', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userroles', verbose_name='user_role'),
        ),
    ]
