# Generated by Django 5.1.5 on 2025-01-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_user_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_surname',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
