# Generated by Django 5.1.5 on 2025-01-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_user_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_tax_number',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
    ]
