version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: school_management_mysql
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    # Запустим на 3307 хостовой машины, чтобы не мешал локальный mysql
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    # (необязательно) healthcheck:
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy  # если используете healthcheck
    env_file:
      - .env
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"

volumes:
  db_data: