# Generated by Django 5.1.5 on 2025-01-25 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineType',
            fields=[
                ('discipline_id', models.AutoField(primary_key=True, serialize=False, verbose_name='discipline_id')),
                ('discipline_name', models.CharField(max_length=255, verbose_name='discipline_name')),
            ],
            options={
                'verbose_name': 'Discipline',
                'verbose_name_plural': 'Disciplines',
                'db_table': 'disciplines',
                'ordering': ['discipline_id'],
            },
        ),
        migrations.CreateModel(
            name='TeacherDiscipline',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('discipline_id', models.ForeignKey(db_column='discipline_id', on_delete=django.db.models.deletion.CASCADE, to='timetable.disciplinetype', verbose_name='discipline_id')),
                ('teacher_id', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='teacher_id')),
            ],
        ),
        migrations.CreateModel(
            name='Timetables',
            fields=[
                ('time_table_id', models.AutoField(primary_key=True, serialize=False, verbose_name='time_table_id')),
                ('time_table_cabinet', models.SmallIntegerField(verbose_name='time_table_cabinet')),
                ('time_table_start_time', models.TimeField(verbose_name='time_table_start_time')),
                ('time_table_end_time', models.TimeField(verbose_name='time_table_end_time')),
                ('time_table_day', models.CharField(max_length=10, verbose_name='time_table_day')),
                ('time_table_discipline_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.disciplinetype', verbose_name='time_table_discipline_ref')),
                ('time_table_group_id_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.usergroup', verbose_name='time_table_group_id_ref')),
            ],
            options={
                'verbose_name': 'Timetable',
                'verbose_name_plural': 'Timetables',
                'db_table': 'time_table',
                'ordering': ['time_table_id'],
            },
        ),
    ]
