# Generated by Django 5.1.5 on 2025-01-26 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherdiscipline',
            options={'ordering': ['id'], 'verbose_name': 'TeacherDiscipline', 'verbose_name_plural': 'TeacherDisciplines'},
        ),
        migrations.AlterModelTable(
            name='teacherdiscipline',
            table='teacher_discipline',
        ),
    ]
