# Generated by Django 5.1.5 on 2025-01-26 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
        ('timetable', '0002_alter_teacherdiscipline_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetables',
            name='time_table_discipline_ref',
            field=models.ForeignKey(db_column='time_table_discipline_ref', null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.disciplinetype', verbose_name='time_table_discipline_ref'),
        ),
        migrations.AlterField(
            model_name='timetables',
            name='time_table_group_id_ref',
            field=models.ForeignKey(db_column='time_table_group_id_ref', null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.usergroup', verbose_name='time_table_group_id_ref'),
        ),
    ]
