# Generated by Django 5.1.5 on 2025-01-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_alter_timetables_time_table_discipline_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetables',
            name='time_table_day',
            field=models.CharField(choices=[('Понеділок', 'Понеділок'), ('Вівторок', 'Вівторок'), ('Середа', 'Середа'), ('Четвер', 'Четвер'), ("П'ятниця", "П'ятниця"), ('Субота', 'Субота'), ('Неділя', 'Неділя')], max_length=10, verbose_name='time_table_day'),
        ),
    ]
