# Generated by Django 5.1.5 on 2025-01-25 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homeworks', '0001_initial'),
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkTypes',
            fields=[
                ('mark_type_id', models.AutoField(primary_key=True, serialize=False, verbose_name='mark_type_id')),
                ('mark_type_name', models.CharField(max_length=255, verbose_name='mark_type_name')),
            ],
            options={
                'verbose_name': 'Mark Type',
                'verbose_name_plural': 'Mark Types',
                'db_table': 'mark_types',
                'ordering': ['mark_type_id'],
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('mark_id', models.AutoField(primary_key=True, serialize=False, verbose_name='mark_id')),
                ('mark_value', models.IntegerField(verbose_name='mark_value')),
                ('mark_created_at', models.DateField(auto_now_add=True, verbose_name='mark_created_at')),
                ('homework_id_ref', models.ForeignKey(db_column='homework_id_ref', on_delete=django.db.models.deletion.CASCADE, to='homeworks.homeworks', verbose_name='homework_id')),
                ('mark_discipline_type_ref', models.ForeignKey(db_column='mark_discipline', on_delete=django.db.models.deletion.CASCADE, to='timetable.disciplinetype', verbose_name='mark_discipline')),
                ('mark_student_id', models.ForeignKey(db_column='mark_student_id', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_marks', to=settings.AUTH_USER_MODEL, verbose_name='mark_student_id')),
                ('mark_teacher_id', models.ForeignKey(db_column='mark_teacher_id', on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to=settings.AUTH_USER_MODEL, verbose_name='mark_teacher_id')),
                ('mark_type', models.ForeignKey(db_column='mark_type', on_delete=django.db.models.deletion.CASCADE, to='marks.marktypes', verbose_name='mark_type')),
            ],
            options={
                'verbose_name': 'Mark',
                'verbose_name_plural': 'Marks',
                'db_table': 'marks',
                'ordering': ['mark_id'],
            },
        ),
    ]
