# Generated by Django 5.1.5 on 2025-01-26 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0002_initial'),
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='homework_id_ref',
            field=models.ForeignKey(db_column='homework_id_ref', null=True, on_delete=django.db.models.deletion.CASCADE, to='homeworks.homeworks', verbose_name='homework_id'),
        ),
    ]
