# Generated by Django 5.1.5 on 2025-02-14 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0004_homeworks_home_work_discipline_ref'),
        ('marks', '0003_alter_marks_mark_discipline_type_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='homework_id_ref',
            field=models.ForeignKey(blank=True, db_column='homework_id_ref', default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='homeworks.homeworks', verbose_name='homework_id'),
        ),
    ]
