# Generated by Django 5.1.5 on 2025-01-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkResponses',
            fields=[
                ('home_work_response_id', models.AutoField(primary_key=True, serialize=False, verbose_name='home_work_response_id')),
                ('home_work_response', models.TextField(verbose_name='homework_response')),
                ('home_work_response_created_at', models.DateTimeField(auto_now_add=True, verbose_name='home_work_response_created_at')),
            ],
            options={
                'verbose_name': 'Homework Response',
                'verbose_name_plural': 'Homework Responses',
                'db_table': 'homework_responses',
                'ordering': ['home_work_response_id'],
            },
        ),
        migrations.CreateModel(
            name='Homeworks',
            fields=[
                ('home_work_id', models.AutoField(primary_key=True, serialize=False, verbose_name='home_work_id')),
                ('home_work_name', models.CharField(max_length=255, verbose_name='home_work_name')),
                ('home_work_topic', models.CharField(max_length=255, verbose_name='home_work_topic')),
                ('home_work_description', models.TextField(verbose_name='home_work_description')),
                ('home_work_deadline', models.DateTimeField(verbose_name='home_work_deadline')),
                ('home_work_created_at', models.DateTimeField(auto_now_add=True, verbose_name='home_work_created_at')),
            ],
            options={
                'verbose_name': 'Homework',
                'verbose_name_plural': 'Homeworks',
                'db_table': 'homeworks',
                'ordering': ['home_work_id'],
            },
        ),
    ]
