# Generated by Django 5.1.5 on 2025-01-25 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_initial'),
        ('homeworks', '0001_initial'),
        ('marks', '0001_initial'),
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkresponses',
            name='home_work_mark_id_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marks.marks', verbose_name='home_work_mark_id_ref'),
        ),
        migrations.AddField(
            model_name='homeworkresponses',
            name='home_work_user_id_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='home_work_user_id_ref'),
        ),
        migrations.AddField(
            model_name='homeworks',
            name='home_work_group_id_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.usergroup', verbose_name='home_work_group_id_ref'),
        ),
        migrations.AddField(
            model_name='homeworks',
            name='home_work_timetable_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.timetables', verbose_name='home_work_timetable_ref'),
        ),
        migrations.AddField(
            model_name='homeworks',
            name='home_work_user_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='homework_user_ref'),
        ),
        migrations.AddField(
            model_name='homeworkresponses',
            name='home_work_id_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeworks.homeworks', verbose_name='home_work_id_ref'),
        ),
    ]
