# Generated by Django 5.1.5 on 2025-01-26 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
        ('homeworks', '0002_initial'),
        ('marks', '0002_alter_marks_homework_id_ref'),
        ('timetable', '0002_alter_teacherdiscipline_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkresponses',
            name='home_work_id_ref',
            field=models.ForeignKey(db_column='home_work_id_ref', on_delete=django.db.models.deletion.CASCADE, to='homeworks.homeworks', verbose_name='home_work_id_ref'),
        ),
        migrations.AlterField(
            model_name='homeworkresponses',
            name='home_work_mark_id_ref',
            field=models.ForeignKey(db_column='home_work_mark_id_ref', null=True, on_delete=django.db.models.deletion.CASCADE, to='marks.marks', verbose_name='home_work_mark_id_ref'),
        ),
        migrations.AlterField(
            model_name='homeworkresponses',
            name='home_work_user_id_ref',
            field=models.ForeignKey(db_column='home_work_user_id_ref', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='home_work_user_id_ref'),
        ),
        migrations.AlterField(
            model_name='homeworks',
            name='home_work_group_id_ref',
            field=models.ForeignKey(db_column='home_work_group_id_ref', null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.usergroup', verbose_name='home_work_group_id_ref'),
        ),
        migrations.AlterField(
            model_name='homeworks',
            name='home_work_timetable_ref',
            field=models.ForeignKey(db_column='home_work_timetable_ref', null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.timetables', verbose_name='home_work_timetable_ref'),
        ),
    ]
