# Generated by Django 5.1.5 on 2025-01-29 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0003_alter_homeworkresponses_home_work_id_ref_and_more'),
        ('timetable', '0004_alter_timetables_time_table_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworks',
            name='home_work_discipline_ref',
            field=models.ForeignKey(db_column='home_work_discipline_ref', null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.disciplinetype', verbose_name='home_work_discipline_ref'),
        ),
    ]
